#+TITLE: An Alternative to Zotero's BibTeX Export

* What This Is

This repository contains a small number of tweaks to Zotero's existing BibTeX export facilities.  They are in the form of modified BibTeX export translators which you can drop into your zotero/translators folder and use for export.  This is easy enough to do, and keeps Zotero's existing BibTeX intact.

It has no user interface, or preferences to set.  It's just a few modified versions of Zotero's standard BibTeX export file, which you can find in '[somedir]/zotero/translators/BibTeX.js'  If you want to change anything, you have to edit the Javascript yourself.  This is a little daunting if you've never done it before, but it's not rocket science either.  I hope in time to comment the files better to make them easier for you to make your own edits.

My initial aim is just to make the modifications I have made available to anyone who finds them useful.  I'll also consider including modifications that other Zotero/BibTeX users find useful--- if necessary by creating multiple different BibTeX-Export files from which you can (here) select.

This started because I couldn't find a BibTeX postprocessor that would meet my needs.  Nor did I really relish the thought of using one every time I update a few database entries and want to see the output in my PDF right away. 

Because of the non standardized nature of BibTeX, Zotero's BibTeX export can't produce the perfect output for all users.  The choices for dealing with that are either to: find a BibTeX (.bst) file which handles Zotero's output and does what you want.  Tweak such a .bst file to handle all the data that Zotero gives it but still outputs only the data you want.  Postprocess your Zotero-exported BibTeX to get what you want or (what I have done here) go all the way back to the source and get Zotero to output BibTeX how you want it in the first place.  Many users will have to use some combination of these.  Follow your bliss.  This was mine.

* The BibTeX Exporters

** BibTeX (Low-Fat)

This makes the following changes from Zotero's standard BibTeX export:

1)  Some fields are not exported.  This is to prevent eager BibTeX styles from adding them to your citations.  

   + ISBN

   + ISSN

   + Library of Congress catalogue number ('lccn')

   + DOI

2)  Some fields are exported only under certain conditions:

  - For any resources suspected of being primarily print-based resources, any URL in the Zotero database is written to the BibTeX database in the "opt_url" field instead of the 'url' field.  This is to prevent bibtex styles from adding the url to citations of such resources  as is still the custom in quaint backwaters where words are still "printed" onto highly processed wood pulp.   We still liberally output the 'url' for other resources.  (The rule is:  a Zotero url goes into 'opt_url' instead of 'url' for all resources which are of the type "book", "thesis" or "book section" or for other resources which have a value in the "pages" field.)  I didn't carefully consider every item type and the conditions under which you might want a URL in the citation.  It's just a simple heuristic to (mostly) do the right thing, and it does what I want.   Instructions are included in the file for writing the URL to the BibTeX 'url' field (Zotero's standard behavior).

Note that although I also added the import of 'opt_url' into Zotero's 'url' field, this won't happen for you even after you install this file, since Zotero still uses its stock BibTeX translator for import.  You may have to replace that one with this, and even then it may not work.  (I haven't tested it).  So for now don't expect data round-tripping.  In practice you can't expect that anyway since there is other data (principally file attachments) which Zotero does not export to BibTeX.

  - The "pages" field is not exported for books
    This is a change that should eventually make it into Zotero's standard BibTeX export.

  - The 'month' field is not exported for articles which have an issue number.  (Cf. for example Chicago Manual of Style 17.161--163)

3) Other changes

  - The quality of the automatically generated keys has been improved (no merged title words, better exclusion of particles from titleword field)
      A patch for this has been submitted to the Zotero dev list to improve it's normal BibTeX export.  It is awaiting approval.

It's easy enough to add any of these back in by uncommenting the appropriate lines in the BibTeX-ScotsClean.js file

** To Use
Drop them in your zotero/translators directory, which is usually within your Firefox profile.  To find out where your zotero data directory is, look in:

Zotero Preferences --> Advanced  --> Show Data Directory

the 'translators' directory is inside that.  When you restart Firefox, the new export will be available in the list.

** To Do

*** TODO Prepare a version with less controversial changes to propose to Zotero's dev team.

*** TODO Add a function to ascii-ize the author's last name and title words of the key rather than just removing the non-ascii letters (that makes for ugly keys)

*** TODO Add the ability to specify what fields do/don't get exported as a variable at the top of the file

*** TODO Do something much more clever with url's .  Instead of omitting them entirely, we should rather either just leave them for web pages (and similar?) or we should omit them from certain resource types (book, article, thesis).  or best: for books and theses, and articles whose data contains a something in the 'pages' field (demonstrating it is a print resource), we should rename the URL field to opt_url

*** TODO Add a link to the attached files in Zotero's storage directory


