#+TITLE: An Alternative to Zotero's BibTeX Export

* What This Is

This repository contains a small number of tweaks to Zotero's existing BibTeX export facilities.  They are in the form of modified BibTeX export translators which you can drop into your zotero/translators folder and use for export.  This is easy enough to do, and keeps Zotero's existing BibTeX intact.

It has no user interface, or preferences to set.  It's just a few modified versions of Zotero's standard BibTeX export file, which you can find in '[somedir]/zotero/translators/BibTeX.js'  If you want to change anything, you have to edit the Javascript yourself.  This is a little daunting if you've never done it before, but it's not rocket science either.  I hope in time to comment the files better to make them easier for you to make your own edits.

My initial aim is just to make the modifications I have made available to anyone who finds them useful.  I'll also consider including modifications that other Zotero/BibTeX users find useful--- if necessary by creating multiple different BibTeX-Export files from which you can (here) select.

This started because I couldn't find a BibTeX postprocessor that would meet my needs.  Nor did I really relish the thought of using one every time I update a few database entries and want to see the output in my PDF right away. 

Because of the non standardized nature of BibTeX, Zotero's BibTeX export can't produce the perfect output for all users.  The choices for dealing with that are listed at the end of this page, but generally involve postprocessing with a script or a BibTeX-aware tool.  Needless to say there are other ways to do these things.  Follow your bliss.  This was mine.

Feel free to contact me with any comments:

scot dot becker at gmail dot com

* The BibTeX Exporters

** BibTeX (Low-Fat)

This makes the following changes from Zotero's standard BibTeX export:

1)  Some fields are not exported.  This is to prevent eager BibTeX styles from adding them to your citations when you don't want them. 

   + ISBN

   + ISSN

   + Library of Congress catalog number ('lccn')

   + DOI

2)  Some fields are exported only under certain conditions:

  - For any resources suspected of being primarily print-based resources, any URL in the Zotero database is written to the BibTeX database in an 'opt_url' field instead of a 'url' field.  This is to prevent BibTeX styles from adding the URL to citations of such resources, thus following the conventions of those quaint backwaters where words are still "printed" onto processed wood pulp.   We still liberally output the URL (to the BibTeX 'url' field) for other resource types.  See "Notes" below for more. 

  - The "pages" field is not exported for books
    (A patch for this has been submitted to the zotero-dev list.)

  - The 'month' field is not exported for articles which have an issue number.  (Cf. for example Chicago Manual of Style 17.161--163)

3) Other changes

  - The quality of the automatically generated keys has been improved (no merged title words, better exclusion of particles from titleword field)  (A patch for this has been submitted to the Zotero dev list to improve it's normal BibTeX export.  It is awaiting testing and approval.)

  - Exported Zotero tags in the LaTeX 'keyword' field are no longer LaTeX escaped.  This makes them easier to read and search.  

It's easy enough to add any of these back in by uncommenting the appropriate lines in the BibTeX-LowCal.js file

It's also not hard to eliminate further fields, like "annote", "extra" or "location".  By throwing a few comments into the file.

** Notes

The rule for exporting the URL is:  a Zotero URL goes into 'opt_url' instead of 'url' for all resources which are of the type "book", "thesis" or "book section" or for other resources which have a value in the "pages" field.  This will not do the right thing if you catalog resources which have both a citable URL and a page range.   It's just a simple heuristic to (mostly) do the right thing, and it does what I want.   Instructions are included in the file for writing the URL to the BibTeX 'url' field (Zotero's standard behavior).

Note that although I also added the import of 'opt_url' into Zotero's 'url' field, this won't happen automatically for you even after you install this file, since Zotero still uses its stock BibTeX translator for import.  You may have to replace that one with this.  (I haven't tested it).  Unless you do this you won't be able to re-import those URL's stored in the 'opt_url' field, so no data round-tripping.  In practice you can't expect that anyway since Zotero export to BibTeX is by nature lossy. (Zotero stores more information than BibTeX, even making use of common extensions).

** To Use
Drop one of the BibTeX-xxxxxx.js files into your zotero/translators directory, which is usually within your Firefox profile.  To find out where your zotero data directory is, look in:

Zotero Preferences --> Advanced  --> Show Data Directory

the 'translators' directory is inside that.  When you restart Firefox, the new export will be available in the list.

** Yet To Do

 + Add a function to ascii-ize the author's last name and title words of the key rather than just removing the non-ascii letters (that makes for ugly keys)

 + Add the ability to specify what fields do/don't get exported as a variable at the top of the file


 + Remove HTML markup from 'notes' field.  At the moment, I get ugly LaTeXification of HTML.  With junk like this:  {\textless}p{\textgreater}

** Wish I could do but probably can't

 + Add a link to the attached files in Zotero's storage directory.  I've looked at the code for this in a few other exporters, but I can't grok it.  If anyone has any ideas how to add this, I'd be happy to hear about it. 

** Alternatives to this approach

If your trouble (like mine) that your BibTeX output from Zotero contains fields you don't want, there are other options to getting what you want.   

(1) Use a BibTeX style which just ignore the extra fields.  Some BibTeX files automatically ignore the 'month' field for journal articles.  You may be able to use one of these or to modify your BibTeX style not to make use of the fields you don't want.

(2) Postprocess your BibTeX files using a text editor, a BibTeX reference manager like JabRef, a scripting language (perl, bash, python or sed) or a dedicated BibTeX postprocessor like 'bibtool' or the new 'bibtexformat'.    

(3) If you use LyX for writing LaTeX, check out the new Firefox plugin LyZ, which maintains a BibTeX based of the works cited in a particular LyX document.

(4) Mendeley has the ability to automatically update its own database based on your Zotero collection (read-only) and to keep a BibTeX file up-to-date with exports from that collection.  Though since Mendeley is a closed-source program you have no control over the BibTeX export, except for the generation of the automatically generated BibTeX keys.  You may still have to make a copy of your BibTeX database and postprocess it (2).

